### ISSUE TITLE
Ideas / todo / etc

### ISSUE THREAD

**Issue by ParmuzinAlexander** [yewang/besogo#21]
If work on the project ever resumes I would like to see the following features.
- [ ] Electron-based app & analysis
- [ ] AI win rate graph support. https://github.com/yewang/besogo/issues/19
- [ ] Last move marker options. `show \ hide \ move number` https://github.com/yewang/besogo/issues/10
